# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tomba < Formula
  desc "CLI utility to search or verify lists of email addresses in minutes."
  homepage "https://tomba.io"
  version "1.0.7"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/tomba-io/tomba/releases/download/v1.0.7/tomba_darwin_amd64.tar.gz"
      sha256 "497aee4e9564982f70856a778aa4241abd5b1ca089ceb2106e30b1f73c5622c4"

      def install
        bin.install "tomba"
        bash_completion.install "./res/package/completion/tomba.bash" => "tomba"
        zsh_completion.install "./res/package/completion/tomba.zsh" => "_tomba"
        fish_completion.install "./res/package/completion/tomba.fish"
        man1.install "./res/package/manpages/tomba.1.gz"
      end
    end
    on_arm do
      url "https://github.com/tomba-io/tomba/releases/download/v1.0.7/tomba_darwin_arm64.tar.gz"
      sha256 "828e0fe999ddf8c635e02f3f4beab7c95cce4d349beca977a1849970906de9d5"

      def install
        bin.install "tomba"
        bash_completion.install "./res/package/completion/tomba.bash" => "tomba"
        zsh_completion.install "./res/package/completion/tomba.zsh" => "_tomba"
        fish_completion.install "./res/package/completion/tomba.fish"
        man1.install "./res/package/manpages/tomba.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tomba-io/tomba/releases/download/v1.0.7/tomba_linux_amd64.tar.gz"
        sha256 "73250b0d22139b9bb8f57fd5f8240ddea1da93b44bbd8883c1a4af21b9b5a651"

        def install
          bin.install "tomba"
          bash_completion.install "./res/package/completion/tomba.bash" => "tomba"
          zsh_completion.install "./res/package/completion/tomba.zsh" => "_tomba"
          fish_completion.install "./res/package/completion/tomba.fish"
          man1.install "./res/package/manpages/tomba.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tomba-io/tomba/releases/download/v1.0.7/tomba_linux_arm64.tar.gz"
        sha256 "4bd847a164d0b2e138faecd278323991bb0997a5effb7cbfb64c11dfb275363e"

        def install
          bin.install "tomba"
          bash_completion.install "./res/package/completion/tomba.bash" => "tomba"
          zsh_completion.install "./res/package/completion/tomba.zsh" => "_tomba"
          fish_completion.install "./res/package/completion/tomba.fish"
          man1.install "./res/package/manpages/tomba.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/tomba version"
  end
end
