# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomba" do
  name "tomba"
  desc "CLI utility to search or verify lists of email addresses in seconds."
  homepage "https://tomba.io"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomba"

  on_macos do
    on_intel do
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_darwin_amd64.tar.gz"
      sha256 "7f908ff04224457a476339741a4aeb5564fb80b34c743f417207d357ce287e33"
    end
    on_arm do
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_darwin_arm64.tar.gz"
      sha256 "69fc820fb48448dddbd3ad79b1d759765f3a86b5436b7142ba3cff208dcebb1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_linux_amd64.tar.gz"
      sha256 "b00cd0bbb74dbb678ebd4945187336faf329b366a5e238dba5e4012b3663cbd1"
    end
    on_arm do
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_linux_arm64.tar.gz"
      sha256 "ea2b6530ab4c73d4450bf868a8f637e2789445bde14c68f1b16ee6e9096d27da"
    end
  end

  # No zap stanza required
end
