# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomba" do
  version "1.1.8"

  on_macos do
    on_arm do
      sha256 "04d7b0f4f9eeb61039057abca7b00b19c558d83adfcdf55f1521b0a050534f0c"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4322b9a7d5fc5644a4e441dc4fc70846acb322dcc6201449d3f7b9311023514e"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b19df483fe2416b343104934d75b904d72e17194a51c5262e9086ca397737031"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7b270d67cb8a369076b63a3870cb80c8469505185c3e1f6a1dbb989e51052af"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_linux_amd64.tar.gz"
    end
  end

  name "tomba"
  desc "CLI utility to search or verify lists of email addresses in seconds."
  homepage "https://tomba.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomba"
  bash_completion "res/package/completion/tomba.bash"
  fish_completion "res/package/completion/tomba.fish"
  zsh_completion "res/package/completion/tomba.zsh"

  # No zap stanza required
end
