# This file was generated by GoReleaser. DO NOT EDIT.
cask "tomba" do
  version "1.1.9"

  on_macos do
    on_arm do
      sha256 "37c2aa1d5f32be32b7373bfef8fd39961b96506631aa5592dbf73fdf06182377"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "25420112e8ecbdff66c496fa1e6f5fcf88677d1b9c6adeb5d52041d6739749f8"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "32a171f3bd396c8b1592c8cfdccd40647a472acf4422ddff9da3372a753c51cf"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87b43ea260b86baa8997c05cb964886f966d9df341ed7a9ed5964d7f1b16d4a1"
      url "https://github.com/tomba-io/tomba/releases/download/v#{version}/tomba_linux_amd64.tar.gz"
    end
  end

  name "tomba"
  desc "CLI utility to search or verify lists of email addresses in seconds."
  homepage "https://tomba.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tomba"
  bash_completion "res/package/completion/tomba.bash"
  fish_completion "res/package/completion/tomba.fish"
  zsh_completion "res/package/completion/tomba.zsh"

  # No zap stanza required
end
